# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0012_auto_20180612_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
