# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0013_auto_20180612_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submited_forms', to='aldryn_forms.FormPlugin'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
