# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 11:49
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('aldryn_forms', '0014_auto_20180612_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='formplugin',
            name='form_detail_field',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='action',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='formplugin',
            name='action_backend',
            field=models.CharField(choices=[('email_only', 'Email only'), ('default', 'Default'), ('none', 'None')], default='default', max_length=15, verbose_name='Action backend'),
        ),
    ]
