# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('aldryn_forms', '0015_auto_20180918_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='formplugin',
            name='include_consents',
            field=models.BooleanField(default=False, verbose_name='Include client consents'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='agreed_consents',
            field=models.ManyToManyField(to='account.Consent'),
        ),
    ]
