# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0016_auto_20180918_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailfieldplugin',
            name='label',
            field=models.CharField(blank=True, max_length=500, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='fieldplugin',
            name='label',
            field=models.CharField(blank=True, max_length=500, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='fileuploadfieldplugin',
            name='label',
            field=models.CharField(blank=True, max_length=500, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='imageuploadfieldplugin',
            name='label',
            field=models.CharField(blank=True, max_length=500, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='textareafieldplugin',
            name='label',
            field=models.CharField(blank=True, max_length=500, verbose_name='Label'),
        ),
    ]
