# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 14:39
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0017_auto_20180918_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formplugin',
            name='form_detail_field',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Form detail'),
        ),
    ]
