# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0019_auto_20181024_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='processing_center',
            field=models.CharField(max_length=5, null=True, verbose_name='Processing center'),
        ),
    ]
